spring.application.name=employee-management-system

# Primary DataSource
spring.datasource.url=jdbc:h2:mem:primarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Secondary DataSource
app.datasource.jdbc-url=jdbc:h2:mem:secondarydb
app.datasource.username=sa
app.datasource.password=password
app.datasource.driver-class-name=org.h2.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true