/*
=========================================================
 Exercise 5 - Triggers
 Scenario 2

 Maintain an audit log for all transactions.
=========================================================
*/

CREATE TABLE AuditLog (

    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    TransactionID NUMBER,

    AccountID NUMBER,

    Amount NUMBER(12,2),

    TransactionType VARCHAR2(20),

    LogDate DATE

);

CREATE OR REPLACE TRIGGER LogTransaction

AFTER INSERT
ON Transactions

FOR EACH ROW

BEGIN

    INSERT INTO AuditLog (

        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        LogDate

    )
    VALUES (

        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE

    );

END;
/