spring.application.name=api-gateway-resilience

server.port=8080

spring.cloud.gateway.routes[0].id=resilience_route
spring.cloud.gateway.routes[0].uri=lb://example-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/service/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=myCircuitBreaker
spring.cloud.gateway.routes[0].filters[1]=FallbackHeaders