spring.application.name=api-gateway

server.port=9090

spring.cloud.gateway.server.webflux.routes[0].id=greet-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/greet/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

logging.level.org.springframework.cloud.gateway=INFO
management.endpoints.web.exposure.include=*